version: '2.2'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: "no"
    ports:
      - ${MSSQL_HOST_PORT}:1433
    volumes:
      - ./docker-data/data:/var/lib/mssqlql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${MSSQL_SA_PASSWORD}